title: Archive of blog.goo.ne.jp/syuusyuu9701
author: syuusyuu9701
description: An archive of the blog originally hosted at https://blog.goo.ne.jp/syuusyuu9701.

theme: minima

plugins:
  - jekyll-feed

baseurl: "/syuusyuu9701"
url: "https://lyroxide.github.io"
