title: Archive of blog.goo.ne.jp/syuusyuu9701
tagline: An archived blog.
author: syuusyuu9701
description: >-
  An archive of the blog originally hosted at https://blog.goo.ne.jp/syuusyuu9701.
  Preserved before its shutdown.
baseurl: "/syuusyuu9701"
url: "https://lyroxide.github.io"

theme: jekyll-theme-chirpy
chirpy_theme:
  skin: auto
  pagination:
    enabled: true
    per_page: 5

tabs:
  - title: Categories
    url: /categories/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
